- name: 'Sandstorm Two Factor Authentication'
  uriPattern: 'neos/two-factor-login'
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Login'
    '@action': 'askForSecondFactor'
    '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Validation'
  uriPattern: 'neos/two-factor-login'
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Authentication'
    '@action': 'checkOtp'
    '@format': 'html'
  httpMethods: ['POST']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Setup'
  uriPattern: 'neos/setup-two-factor-login'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'setupSecondFactor'
      '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true
