Neos:
  Neos:
    fusion:
      autoInclude:
        'Sandstorm.NeosTwoFactorAuthentication': true
    modules:
      management:
        submodules:
          twoFactorAuthentication:
            controller: 'Sandstorm\NeosTwoFactorAuthentication\Controller\BackendController'
            label: 'Sandstorm.NeosTwoFactorAuthentication:Backend:module.label'
            description: 'Sandstorm.NeosTwoFactorAuthentication:Backend:module.description'
            icon: 'fas fa-qrcode'

    userInterface:
      translation:
        autoInclude:
          'Sandstorm.NeosTwoFactorAuthentication':
            - '*'

  Flow:
    http:
      middlewares:
        'secondFactorRedirectMiddleware':
          middleware: 'Sandstorm\NeosTwoFactorAuthentication\Http\Middleware\SecondFactorMiddleware'
          position: 'after securityEntryPoint'
    mvc:
      routes:
        'Sandstorm.NeosTwoFactorAuthentication': true

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sandstorm.NeosTwoFactorAuthentication:SecondFactor':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Sandstorm\NeosTwoFactorAuthentication\Controller\(LoginController|BackendController)'

Sandstorm:
  NeosTwoFactorAuthentication:
    # enforce 2FA for all users
    enforceTwoFactorAuthentication: false
    # (optional) if set this will be used as a naming convention for the TOTP. If empty the Site name will be used
    issuerName: ''
